name: Tests

on:
  push:
  pull_request:

jobs:
  tests:
    name: PHP ${{ matrix.php }}; Symfony ${{ matrix.symfony }}
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        php: ['7.4', '8.0', '8.1', '8.2', '8.3', '8.4']
        symfony: ['4', '5', '6', '7']
        exclude:
          - php: '7.4'
            symfony: '6'
          - php: '7.4'
            symfony: '7'
          - php: '8.0'
            symfony: '7'
          - php: '8.1'
            symfony: '7'
          - php: '8.4'
            symfony: '4'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: none
        env:
          update: true

      - name: Setup Problem Matchers
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Select Symfony 4
        uses: nick-invision/retry@v3
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer require "symfony/event-dispatcher:^4.4" "symfony/filesystem:^4.4" "symfony/process:^4.4" --no-update --no-interaction
        if: "matrix.symfony == '4'"

      - name: Select Symfony 5
        uses: nick-invision/retry@v3
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer require "symfony/event-dispatcher:^5.4" "symfony/filesystem:^5.4" "symfony/process:^5.4" --no-update --no-interaction
        if: "matrix.symfony == '5'"

      - name: Select Symfony 6
        uses: nick-invision/retry@v3
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer require "symfony/event-dispatcher:^6.0" "symfony/filesystem:^6.0" "symfony/process:^6.0" --no-update --no-interaction
        if: "matrix.symfony == '6'"

      - name: Select Symfony 7
        uses: nick-invision/retry@v3
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer require "symfony/event-dispatcher:^7.0" "symfony/filesystem:^7.0" "symfony/process:^7.0" --no-update --no-interaction
        if: "matrix.symfony == '7'"

      - name: Install PHP Dependencies
        uses: nick-invision/retry@v3
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer update --no-interaction --no-progress

      - name: Setup Git
        run: git config --global init.defaultBranch master

      - name: Execute PHPUnit
        run: vendor/bin/phpunit
