name: Tests

on:
  push:
  pull_request:

jobs:
  tests:
    name: PHP ${{ matrix.php }}; Symfony ${{ matrix.symfony }}
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        php: ['7.2', '7.3', '7.4', '8.0', '8.1', '8.2']
        symfony: ['4', '5', '6']
        exclude:
          - php: '7.2'
            symfony: '6'
          - php: '7.3'
            symfony: '6'
          - php: '7.4'
            symfony: '6'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: none

      - name: Setup Problem Matchers
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Select Symfony 4
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer require "symfony/event-dispatcher:^4.4" "symfony/filesystem:^4.4" "symfony/process:^4.4" --no-update --no-interaction
        if: "matrix.symfony == '4'"

      - name: Select Symfony 5
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer require "symfony/event-dispatcher:^5.4" "symfony/filesystem:^5.4" "symfony/process:^5.4" --no-update --no-interaction
        if: "matrix.symfony == '5'"

      - name: Select Symfony 6
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer require "symfony/event-dispatcher:^6.1" "symfony/filesystem:^6.1" "symfony/process:^6.1" --no-update --no-interaction
        if: "matrix.symfony == '6'"

      - name: Install PHP Dependencies
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer update --no-interaction --no-progress

      - name: Setup Git
        run: git config --global init.defaultBranch master

      - name: Execute PHPUnit
        run: vendor/bin/phpunit
