name: Tests

on:
    pull_request:
    push:

jobs:
    tests:
        strategy:
            fail-fast: false
            matrix:
                php:
                    - 7.3
                    - 7.4
                    - 8.0

        runs-on: ubuntu-latest

        name: Tests

        steps:
            -   uses: actions/checkout@v2
            -   run: git fetch --depth=10000

            -   run: git --version

            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    coverage: none

            -   uses: "ramsey/composer-install@v1"

            -   run: |
                  git config --global init.defaultBranch master
                  git config --global user.name "John Doe"
                  git config --global user.email johndoe@example.com

            -   run: vendor/bin/phpunit
